databases:
  - name: bookstore
    databaseName: bookstore
    user: bookstore

services:
  - type: web
    name: bookstore
    runtime: python
    buildCommand: "python manage.py collectstatic --noinput"
    startCommand: "gunicorn bookstore.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookstore
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4